### ISSUE TITLE
Pi 2 support?

### ISSUE THREAD

**Issue by mrkorb** [chrisgjohnson/piglow-sysmon#1]
Compiles without a problem on a Pi model B+, but on the Pi 2 I get the following:

pi@raspberrypi2 ~/piglow/piglow-sysmon $ make
g++ -c -O2 -Wall  piglow-sysmon.cpp -o piglow-sysmon.o
piglow-sysmon.cpp: In function ‘void ChangeOwner(const char*)’:
piglow-sysmon.cpp:153:25: error: ‘getuid’ was not declared in this scope
piglow-sysmon.cpp:153:35: error: ‘getgid’ was not declared in this scope
piglow-sysmon.cpp:153:36: error: ‘chown’ was not declared in this scope
piglow-sysmon.cpp: In function ‘void SetupI2C()’:
piglow-sysmon.cpp:188:10: error: ‘sleep’ was not declared in this scope
piglow-sysmon.cpp: In function ‘void KillExistingInstances(char*)’:
piglow-sysmon.cpp:201:26: error: ‘getpid’ was not declared in this scope
piglow-sysmon.cpp: In function ‘int main(int, char**)’:
piglow-sysmon.cpp:268:46: error: ‘getopt’ was not declared in this scope
piglow-sysmon.cpp:274:25: error: ‘optarg’ was not declared in this scope
piglow-sysmon.cpp:324:21: error: ‘fork’ was not declared in this scope
piglow-sysmon.cpp:346:23: error: ‘usleep’ was not declared in this scope
Makefile:14: recipe for target 'piglow-sysmon.o' failed
make: **\* [piglow-sysmon.o] Error 1

**Comment by chrisgjohnson** [comment]
I don't have a Pi 2 to test this, but try adding

```
#include <unistd.h>
```

after line 35. I'd be glad to know if this works or not.

**Comment by mrkorb** [comment]
That got it to compile!  The CPU temperature monitor doesn't appear to be working though as I'm only getting the left and right arms to light up.

EDIT: Although I suppose maybe I'm just not getting it hot enough to light the first LED.

EDIT 2: Yep.  I wasn't stressing the CPU enough to raise the temp so that it would light an LED.  Thanks for the help!

**Comment by chrisgjohnson** [comment]
Thanks for the bug report! I'll update the code.

It's quite possible that your Pi isn't hot enough to light the first LED: the first LED starts to light at 40°C, and the bar is full at 80°C. My Pi B runs at about 45°C at idle, but this is overclocked and in a case, so quite possibly hotter than average.

Changing line 342 (or line 343 with the additional #include line as above) to

```
PiGlowBar(0, (temp-20.0)/60.0, ledBrightness);
```

will have the bar scale from 20°C to 80°C.

On the Pi B with raspbian (and hopefully on a Pi 2 as well?), you can check the temperature at the command line by running

```
cat /sys/class/thermal/thermal_zone0/temp
```

Divide the result by 1000 to get the temperature in °C.

**Comment by mrkorb** [comment]
`/opt/vc/bin/vcgencmd measure_temp`

Also gives the current temp in C.

`temp=40.1'C`
