### ISSUE TITLE
Reduce the maximum bandwidth 

### ISSUE THREAD

**Issue by ErikLentz** [chrisgjohnson/piglow-sysmon#3]
I really love this little system monitor, it gives my PiGlow new life. My only question is whether piglow-sysmon can use a maximum network threshold of less than 100Mb/s, given that a Pi, especially a model B, won't ever reach that maximum threshold. Something like 20Mb/s would be more practical.

If not, oh well, but at least I thought I would ask.

**Comment by chrisgjohnson** [comment]
Thanks for your kind comments. I've just pushed a new commit that should add a command-line option `-e bits-per-second` that should allow you to specify the network traffic corresponding to a fully illuminated bar. So
`piglow-sysmon -e 20000000` would set a threshold of your suggested 20Mb/s.

I don't have a Pi with a free GPIO port at the moment so I haven't tested this. I'd be grateful if you could give it a go and let me know if it works as expected.

**Comment by ErikLentz** [comment]
It works! Thanks!
